---
title: "tidyr data analysis"
author: "20122011_thomaskutty"
date: "01/01/2021"
output: word_document
---
```{r message=FALSE, warning=FALSE}
library(tidyr)
library(data.table)
```

data.table is more useful in some cases and it is different from data.frame 

Making the data 

```{r}
comp = c(1,1,1,2,2,2,3,3,3)
yr = c(1998,1999,2000,1998,1999,2000,1998,1999,2000) 
q1 = runif(9,min = 0, max = 100)
q2 = runif(9,min = 0, max = 100)
q3 = runif(9,min = 0, max = 100)
q4 = runif(9,min = 0, max = 100)
df = data.frame(comp = comp, year = yr, Qtr1 = q1,
                Qtr2 = q2,Qtr3 = q3,Qtr4 = q4)
df
```

```{r}
gather(df, Quarter, Revenue, Qtr1:Qtr4)
```
gather function is useful in sales analysis and timeseries analysis
here we gather columns into key - value pairs

we can use pipe opertor also for gather 

```{r}
df %>% gather(Quater , Revenue, Qtr1: Qtr4)
```

creating new data 
```{r}
stocks = data.frame(
    time  = as.Date("2009-01-01") + 0:9, 
    x = rnorm(10,0,1),
    y = rnorm(10,0,2),
    z = rnorm(10,0,4)
)
stocks
```


```{r}
stocks.gathered = stocks %>% gather(stock,price, x,y,z)
stocks.gathered
```


```{r}
stocks.gathered %>% spread(stock,price)
```


```{r}
spread(stocks.gathered, time , price)
```


seperator 

```{r}
df = data.frame(new.col = c(NA, "a - x" , "b - y", "c - z")) 
df
```
```{r}
separate(df, col = new.col, into = c("abc", "xyz"))
```


```{r}
df.sep = separate(df, col = new.col, into = c("abc", "xyz"))
df.sep
```


uniting 
```{r}
unite(df.sep, new.joined.col, abc, xyz)
```

```{r}
unite(df.sep, new.joined.col, abc,  xyz, sep = "---")

```

